theme: jekyll-theme-minimal
title: Michael Perreault - Self Taught Full Stack Web Dev
description: Barebones collection of handy (and not so handy) web apps, coded in some mix of python, javascript, react, svelte, and whatever else there is out there.
