theme: jekyll-theme-minimal
title: Michael Perreault - Self Taught Full Stack Web Dev
description: Barebones collection of handy (and not so handy) web apps, coded in some mix of Javascript, React, and a little of everything else.